apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ex14-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: myapp-ex14
      containers:
      - name: my-nginx
        image: nginx:latest
        ports:
        - containerPort: 11000
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 252Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
