apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ex9-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: myapp:v1
        ports:
        - containerPort: 4444
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 252Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 4444
          initialDelaySeconds: 1
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 4444
          initialDelaySeconds: 1
          periodSeconds: 2
