apiVersion: v1
kind: Pod
metadata:
  name: my-nginx2
  labels:
    name: my-nginx2
spec:
  containers:
  - name: my-nginx2
    image: nginx:naoexiste
    ports:
    - name: http
      containerPort: 80
