apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ex7-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: myapp:v1
        ports:
        - containerPort: 4444
