apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ex11-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: myapp:v2
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 252Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 2
        env:
          - name: PORT
            value: "8888"
