apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    name: my-app
spec:
  containers:
  - name: my-nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
  - name: my-app
    image: myapp:test1
    ports:
    - name: http
      containerPort: 4444
