apiVersion: v1
kind: Pod
metadata:
  name: ex4-app
  labels:
    name: ex4-app
spec:
  containers:
  - name: my-nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
  - name: ex4-app
    image: myapp:v1
    ports:
    - name: http
      containerPort: 4444
