apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ex8-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: myapp:test1
        ports:
        - containerPort: 4444
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 252Mi
